@extends('layout')
<ul>
IDE:{{$editora->id_editora}}<br>
Nome:{{$editora->nome}}<br>
Morada:{{$editora->morada}}<br>
Observacoes:{{$editora->observacoes}}<br>
Created_at:{{$editora->created_at}}<br>
Updated_at:{{$editora->updated_at}}<br>
Deleted_at:{{$editora->deleted_at}}
</ul>